/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newloan;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class LoanProcessing extends javax.swing.JFrame {
    
    double loanAmount;
    int loanTerm;
    int selectedDuration;
    double interestRate;
    double totalPayment;
    double monthlyPayment;

    /**
     * Creates new form LoanProcessing
     */
    public LoanProcessing() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLoanType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jtxtLoanAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtLoanDuration = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jtxtinterest = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtTotalPay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtMonthlyPayment = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReport = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 215, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 50, 32));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 50, 32));
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 50, 32));
        jLabel3.setText("Quick Loan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(1, 50, 32));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 215, 0));
        jLabel4.setText("Loan Processing");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 11, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 215, 0));
        jLabel5.setText("Loan Information:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 72, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 215, 0));
        jLabel6.setText("Loan Type:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 129, -1, -1));

        jLoanType.setBackground(new java.awt.Color(1, 50, 32));
        jLoanType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLoanType.setForeground(new java.awt.Color(1, 50, 32));
        jLoanType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Type", "Home Loan", "Vehicle Loan", "Personal Loan", "Educational Loan" }));
        jLoanType.setToolTipText("");
        jLoanType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoanTypeActionPerformed(evt);
            }
        });
        jPanel3.add(jLoanType, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 125, -1, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 215, 0));
        jLabel7.setText("Loan Amount:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 129, -1, -1));

        jtxtLoanAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtLoanAmount.setForeground(new java.awt.Color(255, 215, 0));
        jtxtLoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLoanAmountActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtLoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 125, 150, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 215, 0));
        jLabel8.setText("Loan Duration:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 129, -1, -1));

        jtxtLoanDuration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtLoanDuration.setForeground(new java.awt.Color(1, 50, 32));
        jtxtLoanDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Duration", "3 months", "6 months", "12 months", "24 months", "36 months", "48 months", "60 months" }));
        jPanel3.add(jtxtLoanDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 125, -1, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 215, 0));
        jLabel9.setText("Interest Rate:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 223, -1, -1));

        jtxtinterest.setEditable(false);
        jtxtinterest.setBackground(new java.awt.Color(255, 255, 255));
        jtxtinterest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtinterest.setForeground(new java.awt.Color(1, 50, 32));
        jtxtinterest.setBorder(null);
        jtxtinterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtinterestActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtinterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 219, 150, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 215, 0));
        jLabel10.setText("Total Payment:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 223, -1, -1));

        jtxtTotalPay.setEditable(false);
        jtxtTotalPay.setBackground(new java.awt.Color(255, 255, 255));
        jtxtTotalPay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTotalPay.setForeground(new java.awt.Color(1, 50, 32));
        jtxtTotalPay.setBorder(null);
        jPanel3.add(jtxtTotalPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 219, 120, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 215, 0));
        jLabel11.setText("Payment per Month:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 223, -1, -1));

        jtxtMonthlyPayment.setEditable(false);
        jtxtMonthlyPayment.setBackground(new java.awt.Color(255, 215, 0));
        jtxtMonthlyPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtMonthlyPayment.setForeground(new java.awt.Color(1, 50, 32));
        jtxtMonthlyPayment.setBorder(null);
        jPanel3.add(jtxtMonthlyPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 219, 158, 25));

        jButton1.setBackground(new java.awt.Color(255, 215, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(1, 50, 32));
        jButton1.setText("Calculate");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 292, 175, 35));

        jPanel4.setBackground(new java.awt.Color(1, 50, 32));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 3));

        jtxtReport.setBackground(new java.awt.Color(255, 215, 0));
        jtxtReport.setColumns(20);
        jtxtReport.setForeground(new java.awt.Color(1, 50, 32));
        jtxtReport.setRows(5);
        jScrollPane1.setViewportView(jtxtReport);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 345, 876, -1));

        jButton2.setBackground(new java.awt.Color(255, 215, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(1, 50, 32));
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 699, 115, 38));

        jButton3.setBackground(new java.awt.Color(255, 215, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(1, 50, 32));
        jButton3.setText("Accept");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 699, 115, 38));

        jButton4.setBackground(new java.awt.Color(255, 215, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Reset");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 292, 150, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLoanTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoanTypeActionPerformed
        String selectedLoan = (String) jLoanType.getSelectedItem();
        
        switch (selectedLoan){
            case "Home Loan": jtxtinterest.setText("10 Percent");
            break;
            case "Vehicle Loan": jtxtinterest.setText("13 Percent");
            break;
            case "Personal Loan": jtxtinterest.setText("18 Percent");
            break;
            case "Educational Loan": jtxtinterest.setText("5 Percent");
            break;
            default: jtxtinterest.setText("");
            break;
        }
    }//GEN-LAST:event_jLoanTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //User input
        if (jtxtLoanAmount.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter an amount to proceed", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else {
            loanAmount = Double.parseDouble(jtxtLoanAmount.getText());
        }
         selectedDuration = 0;
         switch (jtxtLoanDuration.getSelectedIndex()){
             case 0: selectedDuration = 0;
            break;
            case 1: selectedDuration = 3;
            break;
            case 2: selectedDuration = 6;
            break;
            case 3: selectedDuration = 12;
            break;
            case 4: selectedDuration = 24;
            break;
            case 5: selectedDuration = 36;
            break;
            case 6: selectedDuration = 48;
            break;
            case 7: selectedDuration = 60;
            break;
         }
         
          interestRate = 0.0;
          switch (jLoanType.getSelectedIndex()){
            case 0: interestRate = 0.0;
            break;
            case 1: interestRate = 10.0;
            break;
            case 2: interestRate = 13.0;
            break;
            case 3: interestRate = 18.0;
            break;
            case 4: interestRate = 5.0;
            break;
          }
         
         loanTerm = selectedDuration / 12;
        
        totalPayment = loanAmount + (loanAmount * (interestRate/100) * loanTerm);
        String ttlPay = String.format("%.2f", totalPayment);
        jtxtTotalPay.setText(ttlPay);
        
        monthlyPayment = totalPayment / selectedDuration;
        String MonthPay = String.format("%.2f", monthlyPayment);
        jtxtMonthlyPayment.setText(MonthPay);
        
        jtxtReport.append("\n\t***********\tLoan Management System\t***********\n\n"
                + "\nAmount Of Loan Requested:\t\t\t $ " + loanAmount
                + "\nInterest Rate:\t\t\t " + interestRate
                + "\nNumber Of Payment Months:\t " + selectedDuration
                + "\nPayment per Month:\t\t $ " + monthlyPayment
                + "\nTotal Loan Payment:\t\t $ " + totalPayment);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtinterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtinterestActionPerformed

    }//GEN-LAST:event_jtxtinterestActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jtxtLoanAmount.setText("");
        jtxtTotalPay.setText("");
        jtxtMonthlyPayment.setText("");
        jtxtinterest.setText("");
        jtxtReport.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtxtLoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLoanAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLoanAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanProcessing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jLoanType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtLoanAmount;
    private javax.swing.JComboBox<String> jtxtLoanDuration;
    private javax.swing.JTextField jtxtMonthlyPayment;
    private javax.swing.JTextArea jtxtReport;
    private javax.swing.JTextField jtxtTotalPay;
    private javax.swing.JTextField jtxtinterest;
    // End of variables declaration//GEN-END:variables
}
