/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newloan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class RegisteForm extends javax.swing.JFrame {
    

    /**
     * Creates new form Registration
     */
    public RegisteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtFirstName = new javax.swing.JTextField();
        JtxtLastNames = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jTxtPhoneNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtcity = new javax.swing.JTextField();
        jTxtState = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTxtDOB = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTxtOrgarnization = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTxtJobTitle = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTxtGrossSalary1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTxtConfirmPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(1, 50, 32));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 215, 0));
        jLabel4.setText("Registration Form");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 11, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 215, 0));
        jLabel5.setText("Personal Information:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 47, -1, -1));

        jTxtFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 75, 300, 30));

        JtxtLastNames.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(JtxtLastNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 75, 300, 30));

        jLabel6.setForeground(new java.awt.Color(255, 215, 0));
        jLabel6.setText("First Name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 111, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 215, 0));
        jLabel7.setText("Last Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 111, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 215, 0));
        jLabel8.setText("E-mail:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 205, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 215, 0));
        jLabel9.setText("Phone:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 205, -1, -1));

        jTxtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 300, 30));

        jTxtPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 230, 300, 30));

        jLabel10.setForeground(new java.awt.Color(255, 215, 0));
        jLabel10.setText("example@example.com");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 266, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 215, 0));
        jLabel11.setText("Address:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 291, -1, -1));

        jTxtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 319, 669, 30));

        jLabel12.setForeground(new java.awt.Color(255, 215, 0));
        jLabel12.setText("Street Address");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 355, -1, -1));

        jTxtcity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 375, 300, 30));

        jTxtState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 375, 300, 30));

        jLabel13.setForeground(new java.awt.Color(255, 215, 0));
        jLabel13.setText("City");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 411, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 215, 0));
        jLabel14.setText("State");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 411, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 215, 0));
        jLabel15.setText("Date of Birth:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jTxtDOB.setBackground(new java.awt.Color(1, 50, 32));
        jTxtDOB.setForeground(new java.awt.Color(255, 215, 0));
        jTxtDOB.setText("dd/mm/yyyy");
        jPanel3.add(jTxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 136, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 215, 0));
        jLabel16.setText("Gender:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 140, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(1, 50, 32));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 215, 0));
        jRadioButton1.setText("Male");
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 138, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(1, 50, 32));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 215, 0));
        jRadioButton2.setText("Female");
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 138, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 215, 0));
        jLabel17.setText("Contact Details");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 177, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 215, 0));
        jLabel18.setText("Employment Information:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 436, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 215, 0));
        jLabel19.setText("Organization:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 464, -1, -1));

        jTxtOrgarnization.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtOrgarnization, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 489, 669, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 215, 0));
        jLabel20.setText("Job Title:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 525, -1, -1));

        jTxtJobTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 300, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 215, 0));
        jLabel21.setText("Gross Salary:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 525, -1, -1));

        jTxtGrossSalary1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtGrossSalary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtGrossSalary1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTxtGrossSalary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 550, 300, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 215, 0));
        jLabel22.setText("Create Password");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 591, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 215, 0));
        jLabel23.setText("Fill in the following");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, -1, -1));

        jTxtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 644, 300, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 215, 0));
        jLabel24.setText("Confirm Password:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 619, -1, -1));

        jTxtConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTxtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 644, 300, 30));

        jButton1.setBackground(new java.awt.Color(255, 215, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(1, 50, 32));
        jButton1.setText("Back");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 701, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 215, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(1, 50, 32));
        jButton2.setText("Submit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 701, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 215, 0));
        jLabel25.setText("Enter Password:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 619, -1, -1));

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 740));

        jPanel2.setBackground(new java.awt.Color(255, 215, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 22)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 22)); // NOI18N
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 50, 32));
        jLabel3.setText("Quick Loan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 909, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Home key = new Home();
        key.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jTxtFirstName.setName("First Name");
    JtxtLastNames.setName("Last Name");
    jTxtPhoneNumber.setName("Phone Number");
    jTxtAddress.setName("Address");
    jTxtcity.setName("City");
    jTxtEmail.setName("Email");
    jTxtDOB.setName("Date of Birth");
    jTxtState.setName("State");
    jTxtOrgarnization.setName("Organization");
    jTxtJobTitle.setName("Job Title");
    jTxtGrossSalary1.setName("Gross Salary");
    jTxtPassword.setName("Password");
    jTxtConfirmPassword.setName("Confirm Password");

        JTextField[] textFields = {
        jTxtFirstName, JtxtLastNames, jTxtPhoneNumber, jTxtAddress, jTxtcity,
        jTxtEmail, jTxtDOB, jTxtState, jTxtOrgarnization,
        jTxtJobTitle, jTxtGrossSalary1, jTxtPassword, jTxtConfirmPassword
    };

    // Boolean flags for checking input validity
    boolean allFilled = true;
    boolean passwordsMatch = true;
    StringBuilder alertMessage = new StringBuilder("Please fill in the following fields: ");

    // Check if all fields are filled
    for (JTextField textField : textFields) {
        if (textField.getText().trim().equals("")) {
            allFilled = false;
            alertMessage.append(textField.getName()).append(", ");
        }
    }

    // Check if passwords match
    if (!jTxtPassword.getText().equals(jTxtConfirmPassword.getText())) {
        passwordsMatch = false;
        if (allFilled) {
            alertMessage = new StringBuilder("Passwords do not match.");
        } else {
            alertMessage.append(" Passwords do not match.");
        }
    }

    // Display alert if not all fields are filled or passwords don't match
    if (!allFilled || !passwordsMatch) {
        // Remove the trailing comma and space if fields are missing
        if (alertMessage.charAt(alertMessage.length() - 2) == ',') {
            alertMessage.setLength(alertMessage.length() - 2);
        }
        JOptionPane.showMessageDialog(this, alertMessage.toString());
    } else {
        // Retrieve input values
        String firstName = jTxtFirstName.getText();
        String lastName = JtxtLastNames.getText();
        String gender = jRadioButton1.isSelected() ? "Female" : "Male";
        String dob = jTxtDOB.getText();
        String email = jTxtEmail.getText();
        String phoneNumber = jTxtPhoneNumber.getText();
        String address = jTxtAddress.getText();
        String city = jTxtcity.getText();
        String state = jTxtState.getText();
        String organization = jTxtOrgarnization.getText();
        String jobTitle = jTxtJobTitle.getText();
        String grossSalary = jTxtGrossSalary1.getText();
        String password = jTxtPassword.getText();

        // Database connection and insertion
        try {
            // Database URL, username, and password
            String url = "jdbc:mysql://localhost:3306/trial";
            String user = "root";
            String dbPassword = "";

            // Establish connection
            Connection con = DriverManager.getConnection(url, user, dbPassword);

            // SQL query to insert data
            String query = "INSERT INTO loan_reg (first_name, last_name, gender, dob, email, phone_number, address, city, state, organization, job_title, gross_salary, password) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            // Prepare statement
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, firstName);
            ps.setString(2, lastName);
            ps.setString(3, gender);
            ps.setString(4, dob);
            ps.setString(5, email);
            ps.setString(6, phoneNumber);
            ps.setString(7, address);
            ps.setString(8, city);
            ps.setString(9, state);
            ps.setString(10, organization);
            ps.setString(11, jobTitle);
            ps.setString(12, grossSalary);
            ps.setString(13, password);

            // Execute update
            ps.executeUpdate();

            // Show success message
            JOptionPane.showMessageDialog(this, "Registration Successful!");

            // Close connection
            ps.close();
            con.close();

            // Redirect to home screen
            Home key = new Home();
            key.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database connection failed: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtGrossSalary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtGrossSalary1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtGrossSalary1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtLastNames;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtConfirmPassword;
    private javax.swing.JFormattedTextField jTxtDOB;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtFirstName;
    private javax.swing.JTextField jTxtGrossSalary1;
    private javax.swing.JTextField jTxtJobTitle;
    private javax.swing.JTextField jTxtOrgarnization;
    private javax.swing.JTextField jTxtPassword;
    private javax.swing.JTextField jTxtPhoneNumber;
    private javax.swing.JTextField jTxtState;
    private javax.swing.JTextField jTxtcity;
    // End of variables declaration//GEN-END:variables
}
